### ISSUE TITLE
March 4th update no longer compatible

### ISSUE THREAD

**Issue by curiousTerminal** [Omega172/Blush-Blush-Cheat#3]
![vkJ1wvC1SG](https://github.com/Omega172/Blush-Blush-Cheat/assets/10541724/92e11c22-58d5-4ccc-924d-649c1772d27b)

As of the March 4th update, injecting the cheat DLL into Blush Blush causes this output and a near-instant Unity crash.

**Comment by 5az3** [comment]
and how do we do to make it work again ?


> ![vkJ1wvC1SG](https://private-user-images.githubusercontent.com/10541724/310241135-92e11c22-58d5-4ccc-924d-649c1772d27b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTYyMDYsIm5iZiI6MTcwOTkxNTkwNiwicGF0aCI6Ii8xMDU0MTcyNC8zMTAyNDExMzUtOTJlMTFjMjItNThkNS00Y2NjLTkyNGQtNjQ5YzE3NzJkMjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE2MzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OWY4NjA2MmU1MDQyMTMyYjYxYzc4Y2YyZmQ2YTE5NDY2ZTI0ZGFjYmE3OWVkNGFmYmU0YmQwYmNiNjJiZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BoIMGtG_-MDdUT7Nz819XyuGwDNWNojKa-MFkGnSzV4)
> 
> As of the March 4th update, injecting the cheat DLL into Blush Blush causes this output and a near-instant Unity crash.

**Comment by curiousTerminal** [comment]
I've seen your update but the provided, compiled .dll is still the previous verison. I'm so, way far out of my depth on compiling a new one myself (I tried, but I'm running on 15 year old ActionScript knowledge). Any way you could provide a rebuilt .dll as well?
(and thank you for doing this for free, it's really appreciated)

**Comment by Omega172** [comment]
@curiousTerminal Fixed with: https://github.com/Omega172/Blush-Blush-Cheat/commit/f52999af443c4a5eaef9b31577c8e08eb673a183
Will post new a compiled dll's release in a bit

Issue was with the updated version of mono they use requiring attach to domain, in every separate thread as well as unlike my framework everything in this project isn't ran in a single thread but many separate threads

Also sorry about the wait life is a bitch sometimes, would have fixed this earlier if I could.
